### ISSUE TITLE
Trying to run the project

### ISSUE THREAD

**Issue by dsmic** [HannahLange/HFDSfortJ#1]
I tried to start:

<pre>
python3 run.py -Nx 6 -Ny 10 -Jp 1.0 -Jz 1.0 -t 3.0 -tprime 0.0 -Ne 36 -b1 1 -b2 1 -f 128 -l 1 -nhid 20 -det hidden -dtype real -init Fermi
usage: run.py [-h] [-Nx NX] [-Ny NY] [-Jz JZ] [-Jp JP] [-t T] [-Ne N_ELECS] [-b1 B1] [-b2 B2] [-init MFINIT] [-f FEATURES]
              [-l LAYERS] [-nhid NHID] [-dtype DTYPE]
run.py: error: argument -t/--t: invalid float value: 'prime'

python3 run.py -Nx 6 -Ny 10 -Jp 1.0 -Jz 1.0 -t 3.0 -Ne 36 -b1 1 -b2 1 -f 128 -l 1 -nhid 20 -dtype real -init Fermi
params: Jz= 1.0 Jp= 1.0 = 3.0 Lx= 6 Lt= 10 bounds= 1 1
120
Traceback (most recent call last):
  File "/home/detlef/SCHULE/gutzwille_chatGPT/HFDSfortJ/run.py", line 146, in <module>
    vstate = nk.vqs.MCState(sa, ma, n_samples=n_samples, chunk_size=cs, n_discard_per_chain=32) #defines the variational state object
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/detlef/tmp/anaconda3/envs/netket/lib/python3.12/site-packages/netket/vqs/mc/mc_state/state.py", line 256, in __init__
    self.init(seed, dtype=sampler.dtype)
  File "/home/detlef/tmp/anaconda3/envs/netket/lib/python3.12/site-packages/netket/vqs/mc/mc_state/state.py", line 305, in init
    variables = jax.jit(self._init_fun, out_shardings=par_sharding)(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/detlef/tmp/anaconda3/envs/netket/lib/python3.12/site-packages/netket/vqs/mc/mc_state/state.py", line 226, in <lambda>
    lambda model, *args, **kwargs: model.init(*args, **kwargs), model
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/detlef/SCHULE/gutzwille_chatGPT/HFDSfortJ/src/hiddenfermions_sym.py", line 97, in __call__
    x_refl    = self.gen_reflected_samples(x)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/detlef/SCHULE/gutzwille_chatGPT/HFDSfortJ/src/hiddenfermions_sym.py", line 86, in gen_reflected_samples
    x = jax.lax.cond(self.n_elecs%2==1, self.flip_single_true, self.flip_single_false,x)
                                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: "HiddenFermion" object has no attribute "flip_single_true".
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
</pre>

any help would be great:)

**Comment by HannahLange** [comment]
Hi,

sorry, there was a mistake in the last update, this line had to be remived (see updates). Note that this should only be used for even particle numbers.

Best regards!

**Comment by dsmic** [comment]
Thanks a lot, 
it is really great to have a paper with code.

I am trying to look into ODLRO with periodic boundary conditions...

I was struggling, as I had strange 0 densities at the boundaries, which should not be boundaries in pbc.

I am flying a little bit blind, but I wondered that the ordering of the sites in g.edges() and in 

<code>
    def ft(k_arr, max_val,sigmaz):
      if "OBC" in self.bounds:
        try:
          matrix = initialize_obc(max_val,sigmaz)
        except AssertionError:
          jax.debug.print("Fall back to PBC")
          matrix = []
          for idx,(kx, ky) in enumerate(k_arr[:max_val]):
            kstate = [ft_local_pbc(x,y,kx,ky) for y in range(self.Ly) for x in range(self.Lx)]
            matrix.append(kstate)
      elif self.bounds=="PBC":
        matrix = []
        for idx,(kx, ky) in enumerate(k_arr[:max_val]):
          kstate = [ft_local_pbc(x,y,kx,ky) for y in range(self.Ly) for x in range(self.Lx)]
          matrix.append(kstate)
          #jax.debug.print("{x}",x=(-np.cos(2*np.pi*kx/self.Lx) - np.cos(2*np.pi*ky/self.Ly),kstate,kx,ky))
      return jnp.array(matrix)
</code>


are different.

As a blind test I changed the ordering to 
<code>
[ft_local_pbc(x,y,kx,ky)  for x in range(self.Lx) for y in range(self.Ly)]
</code>

and the energy is dropping, which might indicate the wave function is better now?


Thanks again Detlef
